name: Terraform Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.13.3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Terraform Init
      run: terraform init
    
    - name: Terraform Plan
      run: terraform plan
    
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve
    
    - name: Update kubeconfig
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        aws eks update-kubeconfig --region us-east-1 --name $(terraform output -raw cluster_name)
    
    - name: Deploy Application
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        kubectl apply -f todo-app/k8s/
    
    - name: Wait for LoadBalancer Service
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        echo "Waiting for LoadBalancer service to be ready..."
        kubectl wait --for=jsonpath='{.status.loadBalancer.ingress}' service/todo-app-service --timeout=600s || true
        kubectl get service todo-app-service
    
    - name: Display Application URL
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        echo "Application URL: $(terraform output -raw todo_app_url)"
